# Generated by Django 5.2.6 on 2025-09-10 15:12

import django.core.validators
import django.db.models.deletion
import relacionamentos.validators.funcoes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da pessoa', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name')),
                ('birthdate', models.DateField(help_text='insira sua data de nascimento', verbose_name='Data Nascimento')),
                ('cpf', models.CharField(help_text='insira o seu cpf sem os pontos', max_length=11, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.funcoes.validate_cpf])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Reportar Nome', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Reporter')),
                ('cpf', models.CharField(help_text='Digite seu cpf sem os pontos', max_length=11, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.funcoes.validate_cpf])),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='insira o titulo de reportagem', max_length=100, verbose_name='title')),
                ('pub_date', models.DateField(verbose_name='published in')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
