# Generated by Django 5.1.3 on 2025-09-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aula.base')),
                ('nome', models.CharField(help_text='Digite o nome do Aluno', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor em reais R$', max_digits=10, verbose_name='Preço')),
                ('turno', models.CharField(blank=True, help_text='Digite o turno da aula', max_length=8, null=True)),
                ('nota', models.FloatField(default=0.0, help_text='Digite a nota do aluno')),
            ],
            bases=('aula.base',),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aula.base')),
                ('cod', models.CharField(help_text='Código do perfil', max_length=10)),
                ('nome', models.CharField(help_text='Nome do perfil', max_length=255, unique=True)),
                ('data_nascimento', models.DateField(help_text='Digite sua Data de Nascimento', max_length=10)),
                ('bio', models.CharField(help_text='Fale um pouco sobre você', max_length=255)),
                ('passaporte', models.CharField(help_text='Digite sua Passaporte', max_length=10)),
                ('genero', models.CharField(help_text='Digite sua Genero', max_length=20)),
                ('cidade', models.CharField(help_text='Digite sua Cidade', max_length=255)),
                ('pais', models.CharField(help_text='Digite sua Pais', max_length=10)),
            ],
            bases=('aula.base',),
        ),
    ]
