# Generated by Django 5.1.3 on 2025-08-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(help_text='Digite sua Data de Nascimento', max_length=10)),
                ('bio', models.CharField(help_text='Fale um pouco sobre você', max_length=255)),
                ('passaporte', models.CharField(help_text='Digite sua Passaporte', max_length=10)),
                ('genero', models.CharField(help_text='Digite sua Genero', max_length=9)),
                ('cidade', models.CharField(help_text='Digite sua Cidade', max_length=255)),
                ('pais', models.CharField(help_text='Digite sua Pais', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='nota',
            field=models.FloatField(default=0.0, help_text='Digite a nota do aluno'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor em reais R$', max_digits=10, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='turno',
            field=models.CharField(blank=True, help_text='Digite o turno da aula', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(help_text='Digite o nome do Aluno', max_length=100),
        ),
    ]
